In [124]:
import pickle
import numpy
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import random
import json

df=pd.read_json("data.json")
display(df)


id first_name   last_name  phoneNumber  salary  \
0       1  Alejandra     Hackett  085-777-914  127000   
1       2      Talia    Botsford  442-739-320   90000   
2       3  Salvatore     Shields  465-936-456   87000   
3       4      Logan  Gusikowski  226-027-730  133000   
4       5    Madelyn   Buckridge  159-739-862  123000   
..    ...        ...         ...          ...     ...   
995   996  Magdalena       Grady  053-353-283   89000   
996   997    Triston      Kirlin  021-113-528   89000   
997   998      Nikko       Hintz  039-015-640   84000   
998   999     Rashad   Rosenbaum  660-038-910   81000   
999  1000       Cleo      Klocko  553-354-391   82000   

                      location                job  isManager  
0    San Francisco, California     Data Scientist       True  
1        Boston, Massachusetts  Building Security       True  
2        Boston, Massachusetts          Custodial       True  
3      New York City, New York  Software Engineer       True  
4               Topeka, Kansas      CyberSecurity       True  
..                         ...                ...        ...  
995  San Francisco, California                 HR      False  
996  San Francisco, California   Customer Support      False  
997      Boston, Massachusetts            Finance      False  
998             Topeka, Kansas         Accounting      False  
999      Boston, Massachusetts                 IT      False  

[1000 rows x 8 columns]

In [125]:
from sklearn.linear_model import LogisticRegression

dfe = pd.get_dummies(df, columns=['location','job'])
display(dfe)

X = dfe.iloc[:, 6:]
y = dfe.salary

X_train, X_test, y_train, y_test,= train_test_split(X, y, test_size=0.2, random_state = 42)

model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
pred


id first_name   last_name  phoneNumber  salary  isManager  \
0       1  Alejandra     Hackett  085-777-914  127000       True   
1       2      Talia    Botsford  442-739-320   90000       True   
2       3  Salvatore     Shields  465-936-456   87000       True   
3       4      Logan  Gusikowski  226-027-730  133000       True   
4       5    Madelyn   Buckridge  159-739-862  123000       True   
..    ...        ...         ...          ...     ...        ...   
995   996  Magdalena       Grady  053-353-283   89000      False   
996   997    Triston      Kirlin  021-113-528   89000      False   
997   998      Nikko       Hintz  039-015-640   84000      False   
998   999     Rashad   Rosenbaum  660-038-910   81000      False   
999  1000       Cleo      Klocko  553-354-391   82000      False   

     location_Boston, Massachusetts  location_Hartford, Connecticut  \
0                                 0                               0   
1                                 1                               0   
2                                 1                               0   
3                                 0                               0   
4                                 0                               0   
..                              ...                             ...   
995                               0                               0   
996                               0                               0   
997                               1                               0   
998                               0                               0   
999                               1                               0   

     location_New York City, New York  location_San Francisco, California  \
0                                   0                                   1   
1                                   0                                   0   
2                                   0                                   0   
3                                   1                                   0   
4                                   0                                   0   
..                                ...                                 ...   
995                                 0                                   1   
996                                 0                                   1   
997                                 0                                   0   
998                                 0                                   0   
999                                 0                                   0   

     ...  job_Accounting  job_Building Security  job_Custodial  \
0    ...               0                      0              0   
1    ...               0                      1              0   
2    ...               0                      0              1   
3    ...               0                      0              0   
4    ...               0                      0              0   
..   ...             ...                    ...            ...   
995  ...               0                      0              0   
996  ...               0                      0              0   
997  ...               0                      0              0   
998  ...               1                      0              0   
999  ...               0                      0              0   

     job_Customer Support  job_CyberSecurity  job_Data Scientist  job_Finance  \
0                       0                  0                   1            0   
1                       0                  0                   0            0   
2                       0                  0                   0            0   
3                       0                  0                   0            0   
4                       0                  1                   0            0   
..                    ...                ...                 ...          ...   
995                     0                  0        

array([ 72000,  84000, 112000, 110000,  65000,  89000,  83000, 106000,
        81000,  83000,  65000,  85000,  83000, 106000,  89000,  84000,
       105000, 110000,  65000,  81000,  84000, 108000,  62000,  81000,
       112000,  84000,  72000,  85000,  64000,  84000,  92000,  84000,
        65000,  84000, 110000,  82000,  84000, 108000,  72000,  84000,
        82000,  85000,  64000, 108000,  84000,  81000, 108000,  72000,
        81000,  91000, 110000,  83000,  65000,  82000, 110000, 110000,
        85000, 110000,  62000, 110000,  87000, 108000,  61000,  81000,
       115000,  63000,  64000,  87000, 105000, 103000,  85000, 116000,
       105000,  65000,  74000,  83000,  64000,  83000,  84000,  89000,
        83000,  92000,  93000,  89000,  89000,  82000,  82000, 107000,
       110000,  81000,  61000,  62000,  74000,  98000,  91000,  83000,
       107000,  82000, 110000,  92000,  87000,  65000,  85000,  87000,
        82000, 108000, 108000,  91000,  82000,  85000,  98000, 110000,
      

In [126]:
accuracy = accuracy_score(y_test, pred)
print(accuracy)

0.12


In [127]:
dfetwo = pd.get_dummies(df, columns=['location','job'])
model.predict(dfetwo[10:11].iloc[:, 6:])


array([110000], dtype=int64)

In [132]:
location_for_predict = input("What is Your location?")
str(location_for_predict)
job_for_predict = input("What is your assumed job?")
str(job_for_predict)
dftester = df
dftester.loc[10,"location"] = location_for_predict
dftester.loc[10,"job"] = job_for_predict

#display(dftester[10:11])
dftestprepped = pd.get_dummies(dftester, columns=['location','job'])
model.predict(dftestprepped[10:11].iloc[:, 6:])
display(dftestprepped[10:11].iloc[:, 6:])

What is Your location?Topeka, Kansas
What is your assumed job?HR


location_Boston, Massachusetts  location_Hartford, Connecticut  \
10                               0                               0   

    location_New York City, New York  location_San Francisco, California  \
10                                 0                                   0   

    location_Topeka, Kansas  job_Accounting  job_Building Security  \
10                        1               0                      0   

    job_Custodial  job_Customer Support  job_CyberSecurity  \
10              0                     0                  0   

    job_Data Scientist  job_Finance  job_HR  job_IT  job_Software Engineer  
10                   0            0       1       0                      0

In [70]:
dftester.loc[10,"location"] = ("horse")
display(dftester.loc[10,"location"])

'horse'

In [112]:
filename = "salarypredict.pkl"
with open(filename, 'wb') as file:
    pickle.dump(model, file)

In [75]:
print(X_test)

     location_Bangalore, Maine  location_Boston, Massachusetts  \
521                          0                               0   
737                          1                               0   
740                          1                               0   
660                          0                               0   
411                          0                               1   
..                         ...                             ...   
436                          0                               0   
764                          0                               1   
88                           0                               0   
63                           0                               1   
826                          0                               1   

     location_Hartford, Connecticut  location_New York City, New York  \
521                               0                                 1   
737                               0                          

In [83]:
print(X_test.loc[521])

location_Bangalore, Maine           0
location_Boston, Massachusetts      0
location_Hartford, Connecticut      0
location_New York City, New York    1
job_Accounting                      0
job_Building Security               1
job_Custodial                       0
job_Customer Support                0
job_CyberSecurity                   0
job_Data Engineer                   0
job_Data Scientist                  0
job_Finance                         0
job_HR                              0
job_Software Engineer               0
Name: 521, dtype: uint8


In [90]:
model.predict(X_test[521:522].reshape(1, -1))

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [113]:
with open('data.json') as f:
    data = json.load(f)
    
df = pd.json_normalize(data['employees'], 
                     meta=['first_name', 'last_name', 'phone_number', 'salary', 'location', 'job'])
pkl_model = pickle.load(open('salarypredict.pkl', 'rb'))

location_for_predict = input("What is Your location?")
str(location_for_predict)
job_for_predict = input("What is your assumed job?")
str(job_for_predict)
dftester = df
dftester.loc[10,"location"] = location_for_predict
dftester.loc[10,"job"] = job_for_predict

dftestprepped = pd.get_dummies(df, columns=['location','job'])
pkl_model.predict(dftestprepped[10:11].iloc[:, 6:])

What is Your location?Topeka, Kansas
What is your assumed job?Software Engineer


array([110000], dtype=int64)