In [115]:
import pickle
import numpy
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import random
import json

df=pd.read_json("data.json")
#display(df)

with open('data.json') as f:
    data = json.load(f)
    
df = pd.json_normalize(data['employees'], 
                     meta=['first_name', 'last_name', 'phone_number', 'salary', 'location', 'job'])

display(df)

id first_name last_name  phoneNumber  salary  \
0       1        Ava  Baumbach  933-532-558  122000   
1       2     Bessie   Windler  783-499-523   96000   
2       3   Yessenia      Moen  669-709-775   87000   
3       4       Jace    Wehner  196-416-907  124000   
4       5    Shakira   D'Amore  576-022-021  130000   
..    ...        ...       ...          ...     ...   
995   996    Nichole      Funk  113-893-857   84000   
996   997     Jaclyn     Price  791-588-693   94000   
997   998       John    Casper  230-768-052   90000   
998   999     Aileen    Stokes  561-070-437   90000   
999  1000    Rogelio   Flatley  404-585-732   86000   

                      location                job  isManager  
0               Topeka, Kansas     Data Scientist       True  
1      New York City, New York  Building Security       True  
2               Topeka, Kansas          Custodial       True  
3        Boston, Massachusetts  Software Engineer       True  
4               Topeka, Kansas      CyberSecurity       True  
..                         ...                ...        ...  
995  San Francisco, California                 HR      False  
996    New York City, New York   Customer Support      False  
997  San Francisco, California            Finance      False  
998             Topeka, Kansas         Accounting      False  
999      Boston, Massachusetts                 IT      False  

[1000 rows x 8 columns]

In [117]:
from sklearn.linear_model import LogisticRegression

dfe = pd.get_dummies(df, columns=['location','job'])
display(dfe)

X = dfe.iloc[:, 6:]
y = dfe.salary

X_train, X_test, y_train, y_test,= train_test_split(X, y, test_size=0.2, random_state = 42)

model = LogisticRegression()
model.fit(X_train, y_train)
pred = model.predict(X_test)
pred


id first_name last_name  phoneNumber  salary  isManager  \
0       1        Ava  Baumbach  933-532-558  122000       True   
1       2     Bessie   Windler  783-499-523   96000       True   
2       3   Yessenia      Moen  669-709-775   87000       True   
3       4       Jace    Wehner  196-416-907  124000       True   
4       5    Shakira   D'Amore  576-022-021  130000       True   
..    ...        ...       ...          ...     ...        ...   
995   996    Nichole      Funk  113-893-857   84000      False   
996   997     Jaclyn     Price  791-588-693   94000      False   
997   998       John    Casper  230-768-052   90000      False   
998   999     Aileen    Stokes  561-070-437   90000      False   
999  1000    Rogelio   Flatley  404-585-732   86000      False   

     location_Boston, Massachusetts  location_Hartford, Connecticut  \
0                                 0                               0   
1                                 0                               0   
2                                 0                               0   
3                                 1                               0   
4                                 0                               0   
..                              ...                             ...   
995                               0                               0   
996                               0                               0   
997                               0                               0   
998                               0                               0   
999                               1                               0   

     location_New York City, New York  location_San Francisco, California  \
0                                   0                                   0   
1                                   1                                   0   
2                                   0                                   0   
3                                   0                                   0   
4                                   0                                   0   
..                                ...                                 ...   
995                                 0                                   1   
996                                 1                                   0   
997                                 0                                   1   
998                                 0                                   0   
999                                 0                                   0   

     ...  job_Accounting  job_Building Security  job_Custodial  \
0    ...               0                      0              0   
1    ...               0                      1              0   
2    ...               0                      0              1   
3    ...               0                      0              0   
4    ...               0                      0              0   
..   ...             ...                    ...            ...   
995  ...               0                      0              0   
996  ...               0                      0              0   
997  ...               0                      0              0   
998  ...               1                      0              0   
999  ...               0                      0              0   

     job_Customer Support  job_CyberSecurity  job_Data Scientist  job_Finance  \
0                       0                  0                   1            0   
1                       0                  0                   0            0   
2                       0                  0                   0            0   
3                       0                  0                   0            0   
4                       0                  1                   0            0   
..                    ...                ...                 ...          ...   
995                     0                  0                   0            

array([ 68000,  87000, 108000, 108000,  68000,  90000,  87000, 110000,
        83000,  87000,  66000,  87000,  89000, 101000,  90000,  83000,
       108000, 109000,  66000,  85000,  83000, 104000,  66000,  82000,
       112000,  99000,  70000,  87000,  67000,  82000,  87000,  83000,
        68000,  85000, 108000,  83000,  82000, 104000,  66000,  94000,
        90000,  87000,  65000, 104000,  85000,  82000, 104000,  76000,
        85000,  87000, 108000,  83000,  70000,  99000, 110000, 108000,
        82000, 108000,  70000, 108000,  94000, 104000,  65000,  83000,
       105000,  74000,  65000,  87000, 112000, 110000,  94000, 109000,
       104000,  66000,  65000,  85000,  67000,  83000,  85000,  82000,
        94000,  87000,  86000,  82000,  83000,  87000,  90000, 105000,
       101000,  82000,  64000,  68000,  65000,  87000,  82000,  94000,
       104000,  87000, 110000,  89000,  87000,  68000,  87000,  94000,
        87000, 104000, 104000,  94000,  90000,  82000,  90000, 101000,
      

In [118]:
accuracy = accuracy_score(y_test, pred)
print(accuracy)

0.08


In [100]:
dfetwo = pd.get_dummies(df, columns=['location','job'])
model.predict(dfetwo[10:11].iloc[:, 6:])


array([93000], dtype=int64)

In [120]:
location_for_predict = input("What is Your location?")
str(location_for_predict)
job_for_predict = input("What is your assumed job?")
str(job_for_predict)
dftester = df
dftester.loc[10,"location"] = location_for_predict
dftester.loc[10,"job"] = job_for_predict

display(dftester[10:11])
dftestprepped = pd.get_dummies(dftester, columns=['location','job'])
model.predict(dftestprepped[10:11].iloc[:, 6:])

What is Your location?Topeka, Kansas
What is your assumed job?Software Engineer


id first_name last_name  phoneNumber  salary        location  \
10  11      Lukas  MacGyver  411-588-207  102000  Topeka, Kansas   

                  job  isManager  
10  Software Engineer      False

array([110000], dtype=int64)

In [70]:
dftester.loc[10,"location"] = ("horse")
display(dftester.loc[10,"location"])

'horse'

In [112]:
filename = "salarypredict.pkl"
with open(filename, 'wb') as file:
    pickle.dump(model, file)

In [75]:
print(X_test)

     location_Bangalore, Maine  location_Boston, Massachusetts  \
521                          0                               0   
737                          1                               0   
740                          1                               0   
660                          0                               0   
411                          0                               1   
..                         ...                             ...   
436                          0                               0   
764                          0                               1   
88                           0                               0   
63                           0                               1   
826                          0                               1   

     location_Hartford, Connecticut  location_New York City, New York  \
521                               0                                 1   
737                               0                          

In [83]:
print(X_test.loc[521])

location_Bangalore, Maine           0
location_Boston, Massachusetts      0
location_Hartford, Connecticut      0
location_New York City, New York    1
job_Accounting                      0
job_Building Security               1
job_Custodial                       0
job_Customer Support                0
job_CyberSecurity                   0
job_Data Engineer                   0
job_Data Scientist                  0
job_Finance                         0
job_HR                              0
job_Software Engineer               0
Name: 521, dtype: uint8


In [90]:
model.predict(X_test[521:522].reshape(1, -1))

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [113]:
with open('data.json') as f:
    data = json.load(f)
    
df = pd.json_normalize(data['employees'], 
                     meta=['first_name', 'last_name', 'phone_number', 'salary', 'location', 'job'])
pkl_model = pickle.load(open('salarypredict.pkl', 'rb'))

location_for_predict = input("What is Your location?")
str(location_for_predict)
job_for_predict = input("What is your assumed job?")
str(job_for_predict)
dftester = df
dftester.loc[10,"location"] = location_for_predict
dftester.loc[10,"job"] = job_for_predict

dftestprepped = pd.get_dummies(df, columns=['location','job'])
pkl_model.predict(dftestprepped[10:11].iloc[:, 6:])

What is Your location?Topeka, Kansas
What is your assumed job?Software Engineer


array([110000], dtype=int64)